'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {Citrus,Plus,Clock3,Receipt,TrendingUp,CupSoda,BarChart3,Search,Camera,Check,Sun,Package,ImageIcon,RefreshCw} from 'lucide-react';
import {SellingTimes} from '@/components/selling-times';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Empty} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import {PAYMENT_METHODS,paymentLabel,money,localParts,addDays,TIMEZONE,rankSaleProducts,type SaleRanking,type Product,type Sale} from '@/lib/stand';
type Summary={products:Product[];saleRanking:SaleRanking[];active:{id:string;started:number}|null;metrics:{sales:number;revenue:number;units:number;upsells:number};top:{product_id:string;name:string;units:number;revenue:number}[];hourly:{hour:number;revenue:number;sales:number}[];daily:{day:string;revenue:number;sales:number}[];openMs:number;trackedRevenue:number;latest:Sale[]};
function dollarsToCents(value:string,label:string){if(!/^(?:\d+(?:\.\d{0,2})?|\.\d{1,2})$/.test(value.trim()))throw new Error(`${label}: enter a valid dollar amount with up to two decimal places.`);const cents=Math.round(Number(value)*100);if(!Number.isSafeInteger(cents)||cents<0||cents>1000000000)throw new Error(`${label}: enter an amount from $0 to $10,000,000.`);return cents;}
const hourLabel=(h:number)=>`${h%12||12}${h<12?'am':'pm'}`;
const when=(t:number)=>new Intl.DateTimeFormat('en-US',{timeZone:TIMEZONE,month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(t);
async function api(url:string,options?:RequestInit){const res=await fetch(url,options);const data:any=await res.json();if(res.status===401){window.location.assign('/login');throw new Error('Please sign in again.');}if(!res.ok)throw new Error(data.error||'Could not connect. Please try again.');return data;}
async function action(body:unknown){return api('/api/stand',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <div className="choice-buttons" role="group" aria-label={label}>{items.map(i=><button type="button" key={i.value} aria-pressed={value===i.value} onClick={()=>onChange(i.value)}>{i.label}</button>)}</div>}
function QuantityButtons({value,onChange,label,min=0,disabled=false}:{value:number;onChange:(v:number)=>void;label:string;min?:number;disabled?:boolean}){
 const [more,setMore]=useState(false);
 return <div className="quantity-picker">
  <div className="quantity-heading"><span>Quantity: <b>{value}</b></span>{min===0&&value>0&&<button type="button" className="quantity-clear" aria-label={`Clear ${label} quantity`} disabled={disabled} onClick={()=>onChange(0)}>Clear</button>}</div>
  <div className="quantity-buttons" role="group" aria-label={`${label} quantity`}>
   {[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={`${label}: ${n}`} aria-pressed={value===n} disabled={disabled} onClick={()=>onChange(min===0&&value===n?0:n)}>{n}</button>)}
   <button type="button" className="quantity-more" aria-label={`More ${label} quantity`} aria-expanded={more||value>5} aria-pressed={value>5} disabled={disabled} onClick={()=>setMore(v=>!v)}>More</button>
  </div>
  {(more||value>5)&&<label className="field quantity-other">Enter quantity<input type="text" inputMode="numeric" pattern="[0-9]*" aria-label={`${label} other quantity`} value={value} disabled={disabled} onChange={e=>{if(/^\d*$/.test(e.target.value))onChange(Math.min(1000,Math.max(min,Number(e.target.value)||min)))}}/></label>}
 </div>
}
function Blank({title,text,children}:{title:string;text:string;children?:React.ReactNode}){return <Empty className="blank"><div className="empty-icon"><Citrus size={28}/></div><h3>{title}</h3><p>{text}</p>{children}</Empty>}
export default function Home(){
 const [tab,setTab]=useState('overview'),[period,setPeriod]=useState('week'),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [data,setData]=useState<Summary|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const [saleOpen,setSaleOpen]=useState(false),[cart,setCart]=useState<Record<string,number>>({}),[customer,setCustomer]=useState(''),[notes,setNotes]=useState(''),[payment,setPayment]=useState('Cash'),[paymentDetails,setPaymentDetails]=useState(''),[photo,setPhoto]=useState<File|null>(null),[photoUrl,setPhotoUrl]=useState(''),[saleError,setSaleError]=useState(''),[saleSearch,setSaleSearch]=useState('');
 const [customItems,setCustomItems]=useState<{key:string;name:string;quantity:string;price:string}[]>([]),[didUpsell,setDidUpsell]=useState(false),[upsellPitch,setUpsellPitch]=useState(''),[upsellItems,setUpsellItems]=useState(''),[paidAmount,setPaidAmount]=useState<string|null>(null),[historyUpsell,setHistoryUpsell]=useState('all');
 const [productOpen,setProductOpen]=useState(false),[editProduct,setEditProduct]=useState<Product|null>(null),[productName,setProductName]=useState(''),[productPrice,setProductPrice]=useState(''),[productColor,setProductColor]=useState('lemon'),[productError,setProductError]=useState('');
 const [query,setQuery]=useState(''),[historyProduct,setHistoryProduct]=useState('all'),[historyPayment,setHistoryPayment]=useState('all'),[page,setPage]=useState(0),[history,setHistory]=useState<{count:number;revenue:number;sales:Sale[]}|null>(null),[historyLoading,setHistoryLoading]=useState(false),[historyError,setHistoryError]=useState('');
 const [detail,setDetail]=useState<Sale|null>(null),[voidOpen,setVoidOpen]=useState(false),[deleteProduct,setDeleteProduct]=useState<Product|null>(null),[clock,setClock]=useState(Date.now());
 const saleId=useRef('');const reload=()=>setRefresh(v=>v+1);
 useEffect(()=>{const id=setInterval(()=>setClock(Date.now()),30000);const fresh=()=>{if(document.visibilityState==='visible')setRefresh(v=>v+1)};window.addEventListener('focus',fresh);document.addEventListener('visibilitychange',fresh);return ()=>{clearInterval(id);window.removeEventListener('focus',fresh);document.removeEventListener('visibilitychange',fresh)}},[]);
 const today=localParts(clock).day;
 const range=period==='custom'?{from,to}:period==='all'?{}:{from:period==='today'?today:addDays(today,period==='week'?-6:-29),to:today};
 const params=new URLSearchParams(range as Record<string,string>).toString();
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError('');try{const d=await api('/api/stand?'+params,{signal});setData(d);}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message);}finally{if(!signal?.aborted)setLoading(false)}},[params]);
 useEffect(()=>{const c=new AbortController();load(c.signal);return ()=>c.abort()},[load,refresh]);
 useEffect(()=>{setPage(0)},[query,historyProduct,historyPayment,historyUpsell,params]);
 useEffect(()=>{if(tab!=='sales')return;const c=new AbortController();setHistoryLoading(true);setHistoryError('');const timer=setTimeout(()=>{api('/api/stand?'+params+'&'+new URLSearchParams({action:'history',q:query,product:historyProduct==='all'?'':historyProduct,payment:historyPayment==='all'?'':historyPayment,upsell:historyUpsell==='all'?'':historyUpsell,page:String(page)}),{signal:c.signal}).then(setHistory).catch(e=>{if(e.name!=='AbortError')setHistoryError(e.message)}).finally(()=>{if(!c.signal.aborted)setHistoryLoading(false)})},200);return()=>{clearTimeout(timer);c.abort()}},[tab,params,query,historyProduct,historyPayment,historyUpsell,page,refresh]);
 useEffect(()=>{if(!photo){setPhotoUrl('');return;}const u=URL.createObjectURL(photo);setPhotoUrl(u);return()=>URL.revokeObjectURL(u)},[photo]);
 function newSale(){setSaleSearch('');saleId.current=crypto.randomUUID();setCart({});setCustomItems([]);setDidUpsell(false);setUpsellPitch('');setUpsellItems('');setPaidAmount(null);setCustomer('');setNotes('');setPhoto(null);setPayment('Cash');setPaymentDetails('');setSaleError('');setSaleOpen(true)}
 const openSaleRef=useRef(newSale);openSaleRef.current=newSale;
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_sale_entry',title:'Start a sale',description:'Open the sale form. This does not save a transaction.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');openSaleRef.current();return {status:'form_opened'};}},{signal:lifecycle.signal})).catch(console.error)}catch(e){console.error(e)}return()=>lifecycle.abort()},[]);
 async function saveSale(e:React.FormEvent){e.preventDefault();setSaleError('');setBusy(true);try{if(payment==='Other'&&!paymentDetails.trim())throw new Error('Tell us what they paid with.');const selected=(data?.products||[]).filter(p=>(cart[p.id]||0)>0).map(p=>({id:p.id,quantity:cart[p.id],price:p.price}));const custom=customItems.map(i=>({name:i.name.trim(),quantity:Number(i.quantity),price:dollarsToCents(i.price,'Custom item price')}));if(!selected.length&&!custom.length)throw new Error('Add at least one product or custom item to this sale.');if(custom.some(i=>!i.name||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>1000||i.price>1000000))throw new Error('Each custom item needs a name, a quantity from 1 to 1,000, and a unit price up to $10,000.');const form=new FormData();form.append('sale',JSON.stringify({id:saleId.current,customer,notes,payment,paymentDetails:payment==='Other'?paymentDetails.trim():'',items:selected,customItems:custom,didUpsell,upsellPitch:didUpsell?upsellPitch:'',upsellItems:didUpsell?upsellItems:'',paidTotal:paidAmount===null?undefined:dollarsToCents(paidAmount,'Amount paid')}));if(photo)form.append('photo',photo);await api('/api/stand',{method:'POST',body:form});setSaleOpen(false);toast.success('Sale saved. Every squeeze counts!');reload();}catch(e){setSaleError((e as Error).message)}finally{setBusy(false)}}
 async function changeSession(){setBusy(true);try{await action(data?.active?{action:'close',id:data.active.id}:{action:'open',id:crypto.randomUUID()});toast.success(data?.active?'Stand closed. Selling hours saved.':'You’re open! Your selling time is being tracked.');reload()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 function openProduct(p:Product|null){setEditProduct(p);setProductName(p?.name||'');setProductPrice(p?String(p.price/100):'');setProductColor(p?.color||'lemon');setProductError('');setProductOpen(true)}
 async function saveProduct(e:React.FormEvent){e.preventDefault();setBusy(true);setProductError('');try{const price=Number(productPrice);if(!/^\d+(\.\d{1,2})?$/.test(productPrice)||price>10000)throw new Error('Enter a price between $0 and $10,000, with up to two decimal places.');await action({action:'product',product:{id:editProduct?.id,name:productName,price:Math.round(price*100),color:productColor,archived:editProduct?.archived||0}});setProductOpen(false);toast.success('Menu saved.');reload()}catch(e){setProductError((e as Error).message)}finally{setBusy(false)}}
 async function archiveProduct(p:Product){setBusy(true);try{await action({action:'product',product:{...p,archived:p.archived?0:1}});reload();toast.success(p.archived?'Product restored.':'Product archived. Past sales are preserved.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function starterMenu(){setBusy(true);try{await action({action:'starter-menu'});toast.success('Starter menu added. You can change every name and price.');reload()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function restoreProduct(p:Product){setBusy(true);try{await action({action:'restore-product',id:p.id});toast.success('Product restored.');reload()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function removeProduct(p:Product){setBusy(true);try{await action({action:'delete-product',id:p.id});setDeleteProduct(null);toast.success('Product deleted. Past sales are preserved.',{action:{label:'Undo',onClick:()=>{void restoreProduct(p)}}});reload()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 const products=rankSaleProducts(data?.products||[],data?.saleRanking||[]),m=data?.metrics;
 const saleUnits=new Map((data?.saleRanking||[]).map(r=>[r.id,r.units]));
 const menuProducts=(data?.products||[]).filter(p=>!p.deleted),deletedProducts=(data?.products||[]).filter(p=>!!p.deleted);
 const subtotal=products.reduce((a,p)=>a+(cart[p.id]||0)*p.price,0)+customItems.reduce((a,i)=>a+Math.round((Number(i.price)||0)*100)*(Number(i.quantity)||0),0),total=paidAmount===null?subtotal:Math.round((Number(paidAmount)||0)*100),quantity=Object.values(cart).reduce((a,n)=>a+n,0)+customItems.reduce((a,i)=>a+(Number(i.quantity)||0),0);
 function updateCustom(key:string,field:'name'|'quantity'|'price',value:string){setCustomItems(items=>items.map(i=>i.key===key?{...i,[field]:value}:i))}
 const bestHour=data?.hourly.slice().sort((a,b)=>b.revenue-a.revenue||a.hour-b.hour)[0];
 const activeMinutes=data?.active?Math.max(0,Math.floor((clock-data.active.started)/60000)):0;
 const rankMax=Math.max(1,...(data?.top.map(p=>p.units)||[]));
 return <main className="shell"><Toaster richColors position="top-center"/><header className="topbar"><a className="brand" href="/"><Citrus/><span>sunny squeeze<span className="brand-note">YOUR LEMONADE STAND</span></span></a><div className="header-right"><span className="private-label">Your private stand</span><form action="/api/auth/logout" method="post"><button className="quiet" type="submit">Sign out</button></form><button className="icon-button" aria-label="Refresh sales" onClick={reload} disabled={loading}><RefreshCw size={17}/></button></div></header>
 <div className="intro"><div><p className="eyebrow">A LITTLE STAND. A BIG PICTURE.</p><h1>Every squeeze counts.</h1><p className="muted">Your sales, your customers, your next good day.</p></div><button className="primary log-button" onClick={newSale} disabled={!data||!!error}><Plus size={19}/> Log a sale</button></div>
 <div className={'session-bar '+(data?.active?'is-open':'')}><span><Sun size={20}/><span><b>{data?.active?'Open for good things.':'Ready when you are.'}</b><small>{data?.active?`Stand opened ${when(data.active.started)} · ${Math.floor(activeMinutes/60)}h ${activeMinutes%60}m`:'Track your selling hours for a meaningful hourly average.'}</small></span></span><button className="secondary" onClick={changeSession} disabled={busy||!data||!!error}>{data?.active?'Close stand':'Open stand'}</button></div>
 <Tabs value={tab} onValueChange={setTab}><div className="toolbar"><TabsList className="main-tabs" variant="line"><TabsTrigger value="overview"><BarChart3/> Overview</TabsTrigger><TabsTrigger value="sales"><Receipt/> Sales log</TabsTrigger><TabsTrigger value="sessions"><Clock3/> Selling times</TabsTrigger><TabsTrigger value="menu"><CupSoda/> Your menu</TabsTrigger></TabsList>{tab!=='menu'&&tab!=='sessions'&&<div className="date-filter"><Choice label="Reporting period" value={period} onChange={setPeriod} items={[{value:'today',label:'Today'},{value:'week',label:'Last 7 days'},{value:'month',label:'Last 30 days'},{value:'all',label:'All time'},{value:'custom',label:'Custom dates'}]}/>{period==='custom'&&<div className="custom-dates"><input aria-label="From date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>to</span><input aria-label="To date" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div>}</div>}</div>
 {error&&<div className="error" role="alert">{error} <button onClick={reload}>Try again</button></div>}
 {loading&&!data?<div className="stats">{[1,2,3,4].map(i=><Skeleton className="loading-card" key={i}/>)}</div>:null}
 <TabsContent value="overview"><div className="stats" aria-busy={loading}><Metric title="Total revenue" value={m?money(m.revenue):'—'} sub="Before costs · USD" featured icon={<TrendingUp size={18}/>}/><Metric title="Sales" value={String(m?.sales??'—')} sub={`${m?.units??0} items · ${m?.upsells??0} upsold sales`} icon={<Receipt size={18}/>}/><Metric title="Average sale" value={m?.sales?money(m.revenue/m.sales):'—'} sub="Revenue per transaction" icon={<CupSoda size={18}/>}/><Metric title="Revenue / open hour" value={data?.openMs?money(data.trackedRevenue/(data.openMs/3600000)):'—'} sub={data?.openMs?`${(data.openMs/3600000).toFixed(1)} selling hours tracked`:'Open your stand to track hours'} icon={<Clock3 size={18}/>}/></div>
 {data&&!data.products.length&&<div className="onboarding"><div><b>First, make the menu yours.</b><p>Add your products and prices, or start with three lemonade favorites.</p></div><button className="secondary" onClick={()=>{setTab('menu');openProduct(null)}}><Plus size={17}/> Add a product</button><button className="quiet" onClick={starterMenu} disabled={busy}>Use starter menu</button></div>}
 <div className="dashboard-grid"><section className="panel revenue-panel"><div className="panel-heading"><div><p className="eyebrow">THE DAILY POUR</p><h2>Revenue over time</h2></div><span className="pill">{period==='week'?'7 days':period==='month'?'30 days':period==='today'?'Today':period==='all'?'All time':'Custom'}</span></div>{data?.daily.length?<RevenueChart rows={data.daily}/>:<Blank title="Your story starts with a sale." text="Each sale you log adds to the picture here."><button className="secondary" onClick={newSale} disabled={!data}>Log your first sale</button></Blank>}</section>
 <section className="panel favorites"><div className="panel-heading"><div><p className="eyebrow">CROWD FAVORITES</p><h2>Best sellers</h2></div><CupSoda size={21}/></div>{data?.top.length?<div className="rank-list">{data.top.slice(0,5).map((p,i)=><div className="rank" key={p.product_id}><span className="rank-number">0{i+1}</span><div className="rank-main"><div><strong>{data.products.find(x=>x.id===p.product_id)?.name||p.name}</strong><span>{p.units} sold</span></div><div className="rank-track"><div style={{width:`${p.units/rankMax*100}%`}}/></div><small>{money(p.revenue)} in revenue</small></div></div>)}</div>:<Blank title="A favorite is waiting." text="Your most-loved products will show up here."/>}<p className="panel-footnote">Ranked by items sold. Adjusted payments are split across items in proportion to their prices (or quantities for free items).</p></section>
 <section className="panel"><div className="panel-heading"><div><p className="eyebrow">FIND YOUR SWEET SPOT</p><h2>Sales by hour</h2></div>{bestHour&&<span className="pill">Best: {hourLabel(bestHour.hour)}</span>}</div><HourlyChart rows={data?.hourly||[]}/><p className="panel-footnote">Revenue by local hour. {bestHour?`${hourLabel(bestHour.hour)}–${hourLabel((bestHour.hour+1)%24)} earned ${money(bestHour.revenue)} across this period.`:'Log a few sales to discover your busiest time.'}</p></section>
 <section className="panel insight"><div className="insight-icon"><Clock3 size={24}/></div><p className="eyebrow">MAKE YOUR TIME COUNT</p><h2>{data?.openMs?'Your time, accounted for.':'A good day starts with “Open”.'}</h2><p>Open the stand when you start selling, then close it when you finish. Your hourly average uses the time you’re actually open.</p><div className="insight-total"><span>Revenue during open hours</span><strong>{money(data?.trackedRevenue||0)}</strong></div>{!!m&&m.revenue>(data?.trackedRevenue||0)&&<small>{money(m.revenue-(data?.trackedRevenue||0))} logged outside tracked hours is included in total revenue, but not the hourly average.</small>}</section></div>
 <section className="panel recent"><div className="panel-heading"><h2>Fresh off the stand</h2><button className="quiet" onClick={()=>setTab('sales')}>View all sales</button></div><SalesTable sales={data?.latest||[]} onOpen={setDetail}/></section></TabsContent>
 <TabsContent value="sales"><section className="panel sales-panel"><div className="panel-heading"><div><h2>Every sale, remembered.</h2><p className="muted">Find a customer, product, or that one special moment.</p></div><span className="pill">{history?.count??0} sales · {money(history?.revenue||0)}</span></div><div className="search-row"><label className="search"><Search size={18}/><input placeholder="Search customers, products, notes, payments…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search sales"/></label><div className="history-filter"><span>Product</span><Choice label="Filter by product" value={historyProduct} onChange={setHistoryProduct} items={[{value:'all',label:'All products'},...(data?.products||[]).map(p=>({value:p.id,label:p.name+(p.deleted?' (deleted)':'')}))]}/></div><div className="history-filter"><span>Payment</span><Choice label="Filter by payment" value={historyPayment} onChange={setHistoryPayment} items={['all',...PAYMENT_METHODS].map(x=>({value:x,label:x==='all'?'All payments':x}))}/></div><div className="history-filter"><span>Upsell</span><Choice label="Filter by upsell" value={historyUpsell} onChange={setHistoryUpsell} items={[{value:'all',label:'All sales'},{value:'1',label:'Upsold sales'},{value:'0',label:'Not upsold'}]}/></div></div>{historyError&&<p className="error" role="alert">{historyError}</p>}{historyLoading?<p className="muted loading-line">Loading sales…</p>:<SalesTable sales={history?.sales||[]} onOpen={setDetail}/>}<div className="pagination"><span>{history?.count?`Showing ${page*25+1}–${Math.min((page+1)*25,history.count)} of ${history.count}`:'No matching sales'}</span><div><button className="secondary" disabled={!page||historyLoading} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="secondary" disabled={(page+1)*25>=(history?.count||0)||historyLoading} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></section></TabsContent>
 <TabsContent value="sessions"><SellingTimes refresh={refresh} clock={clock} onChange={reload}/></TabsContent>
 <TabsContent value="menu"><section className="panel"><div className="panel-heading"><div><h2>Made to sell.</h2><p className="muted">Your products and prices. Past sales keep their original prices.</p></div><button className="primary" onClick={()=>openProduct(null)}><Plus size={18}/> Add a product</button></div>{!menuProducts.length?<Blank title="What’s on the menu?" text="Add your own products, or use an editable starter menu."><button className="secondary" disabled={busy} onClick={starterMenu}>Use starter menu</button></Blank>:<div className="product-grid">{menuProducts.map(p=><article key={p.id} className={'product-card '+(p.archived?'archived':'')}><div className={'product-icon '+p.color}><CupSoda size={29}/></div><h3>{p.name}</h3><strong>{money(p.price)}</strong><div className="product-actions"><button className="secondary" onClick={()=>openProduct(p)}>Edit</button><button className="quiet" disabled={busy} onClick={()=>archiveProduct(p)}>{p.archived?'Restore':'Archive'}</button><button className="quiet danger" disabled={busy} onClick={()=>setDeleteProduct(p)}>Delete</button></div>{!!p.archived&&<small>Archived · saved in your sales history</small>}</article>)}</div>}{!!deletedProducts.length&&<details className="deleted-menu"><summary>Deleted items ({deletedProducts.length})</summary><p className="muted">These are hidden from your menu and sale form. Past sales stay saved.</p>{deletedProducts.map(p=><div className="deleted-product" key={p.id}><span><b>{p.name}</b><small>{money(p.price)}{p.archived?' · Archived':''}</small></span><button className="secondary" disabled={busy} onClick={()=>restoreProduct(p)}>Restore</button></div>)}</details>}</section></TabsContent>
 </Tabs><footer><span><Citrus size={15}/> One cup at a time.</span><span>USD · Times in {TIMEZONE} · Your stand’s sales and customer records</span></footer>
 <Dialog open={saleOpen} onOpenChange={v=>{if(!busy)setSaleOpen(v)}}><DialogContent className="sale-dialog"><DialogTitle className="modal-title">A little sale. A little sunshine.</DialogTitle><DialogDescription>Choose what you sold. We’ll save the time automatically.</DialogDescription><form onSubmit={saveSale} className="sale-form"><div className="sale-fields"><div className="modal-section"><span className="section-label">What did you sell?</span><p className="sale-order-label">Best sellers first · All-time items sold</p><p className="form-hint quantity-hint">Tap 1–5 to set the quantity, or More for another amount. Tap the selected number again to clear it.</p>{products.length>6&&<label className="search sale-search"><Search size={18}/><input aria-label="Find a product" placeholder="Find a product…" value={saleSearch} onChange={e=>setSaleSearch(e.target.value)}/></label>}{!products.length?<div className="muted">Choose a custom item below, or add products in Your menu.</div>:products.filter(p=>p.name.toLowerCase().includes(saleSearch.toLowerCase())).map(p=><div className={"sale-product "+(cart[p.id]?"is-selected":"")} key={p.id}><span className={'product-icon small '+p.color}><CupSoda size={21}/></span><div className="sale-product-heading"><span className="sale-rank">#{products.findIndex(x=>x.id===p.id)+1}</span><div><b>{p.name}</b><small>{money(p.price)} each · {(saleUnits.get(p.id)||0)>0?`${saleUnits.get(p.id)} sold`:'Not sold yet'}</small></div></div><QuantityButtons label={p.name} value={cart[p.id]||0} disabled={busy} onChange={n=>setCart(c=>({...c,[p.id]:n}))}/></div>)}{!!saleSearch&&!products.some(p=>p.name.toLowerCase().includes(saleSearch.toLowerCase()))&&<p className="muted">No products match. Clear the search or add a custom item.</p>}</div>
 <div className="custom-items"><div className="custom-heading"><span className="section-label">Custom items</span><button className="secondary" type="button" disabled={busy||customItems.length>=50} onClick={()=>setCustomItems(items=>[...items,{key:crypto.randomUUID(),name:'',quantity:'1',price:''}])}><Plus size={16}/> Add custom item</button></div>{customItems.map((i,n)=><div className="custom-item" key={i.key}><label className="field custom-name">Item name<input required maxLength={80} aria-label={`Custom item ${n+1} name`} value={i.name} placeholder="Something else they bought" onChange={e=>updateCustom(i.key,'name',e.target.value)}/></label><QuantityButtons min={1} label={`Custom item ${n+1}`} value={Number(i.quantity)} disabled={busy} onChange={n=>updateCustom(i.key,'quantity',String(n))}/><label className="field">Price each (USD)<input required type="number" min="0" max="10000" step="0.01" inputMode="decimal" aria-label={`Custom item ${n+1} price`} value={i.price} placeholder="0.00" onChange={e=>updateCustom(i.key,'price',e.target.value)}/></label><button type="button" className="quiet" aria-label={`Remove custom item ${n+1}`} onClick={()=>setCustomItems(items=>items.filter(x=>x.key!==i.key))}>Remove</button></div>)}</div>
 <div className="payment-section"><span className="section-label">Paid with</span><Choice label="Payment method" value={payment} onChange={setPayment} items={PAYMENT_METHODS.map(x=>({value:x,label:x}))}/>{payment==='Other'&&<label className="field other-payment-field">What did they pay with?<input required autoFocus maxLength={80} type="text" autoComplete="off" placeholder="e.g. bank transfer or a trade" value={paymentDetails} onChange={e=>setPaymentDetails(e.target.value)}/></label>}</div><div className="amount-paid"><div><span className="section-label">Item subtotal: {money(subtotal)}</span><p className="form-hint">Change the amount below if the customer paid a different total.</p></div><label className="field">Amount paid (USD)<input required type="number" min="0" max="10000000" step="0.01" inputMode="decimal" value={paidAmount??(subtotal/100).toFixed(2)} onChange={e=>setPaidAmount(e.target.value)}/></label>{paidAmount!==null&&<button type="button" className="quiet" onClick={()=>setPaidAmount(null)}>Use item subtotal</button>}</div><label className="upsell-choice"><Checkbox checked={didUpsell} onCheckedChange={v=>setDidUpsell(v===true)} aria-label="Did upsale" aria-controls="upsell-details" aria-expanded={didUpsell}/><span><b>Did upsale</b><small>I suggested something extra and the customer bought it.</small></span></label>
 {didUpsell&&<div id="upsell-details" className="upsell-details"><label className="field">What did you say? <span>Optional</span><textarea rows={3} maxLength={2000} value={upsellPitch} onChange={e=>setUpsellPitch(e.target.value)} placeholder="For example: Would you like a cookie with your lemonade?"/></label><label className="field">What did you upsell? <span>Optional</span><textarea rows={2} maxLength={1000} value={upsellItems} onChange={e=>setUpsellItems(e.target.value)} placeholder="For example: One cookie and a larger lemonade"/></label></div>}
 <label className="field">Customer name <span>Optional</span><input autoComplete="off" maxLength={100} value={customer} placeholder="Who stopped by?" onChange={e=>setCustomer(e.target.value)}/></label><label className="field">Anything special about this sale? <span>Optional</span><textarea maxLength={2000} rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="A regular customer, a big order, a neighborhood event…"/></label><div className="photo-field"><label className="upload"><Camera size={20}/><span>{photo?photo.name:'Add a customer photo'}<small>Optional · JPG, PNG or WebP · up to 5 MB</small></span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>5*1024*1024){setSaleError('Choose a photo smaller than 5 MB.');return;}setSaleError('');setPhoto(f||null)}}/></label>{photoUrl&&<div className="photo-preview"><img src={photoUrl} alt="Selected customer photo"/><button type="button" className="quiet" onClick={()=>setPhoto(null)}>Remove photo</button></div>}</div><p className="form-hint">Only add a customer photo with their permission.</p>{!data?.active&&<p className="form-hint">Your stand timer is closed. This sale will count toward revenue, but not revenue per open hour.</p>}{saleError&&<p className="error" role="alert">{saleError}</p>}</div><div className="sale-total" aria-live="polite"><div><span>{quantity} {quantity===1?'item':'items'}</span><strong>{money(total)}</strong></div><button className="primary" type="submit" disabled={busy||quantity===0}><Check size={19}/>{busy?'Saving…':'Save sale'}</button></div></form></DialogContent></Dialog>
 <Dialog open={productOpen} onOpenChange={v=>{if(!busy)setProductOpen(v)}}><DialogContent><DialogTitle className="modal-title">{editProduct?'Edit your product':'Something new on the menu'}</DialogTitle><DialogDescription>Set a name and price for future sales.</DialogDescription><form className="product-form" onSubmit={saveProduct}><label className="field">Product name<input required maxLength={80} value={productName} onChange={e=>setProductName(e.target.value)} placeholder="Classic lemonade"/></label><label className="field">Price (USD)<input required inputMode="decimal" type="number" step="0.01" min="0" max="10000" value={productPrice} onChange={e=>setProductPrice(e.target.value)} placeholder="3.00"/></label><label className="field">Menu color<Choice label="Product color" value={productColor} onChange={setProductColor} items={[{value:'lemon',label:'Lemon'},{value:'pink',label:'Strawberry'},{value:'mint',label:'Mint'},{value:'orange',label:'Orange'}]}/></label>{productError&&<p className="error" role="alert">{productError}</p>}<button className="primary" disabled={busy} type="submit">{busy?'Saving…':'Save product'}</button></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent className="detail-dialog"><DialogTitle className="modal-title">Sale details</DialogTitle><DialogDescription>{detail&&when(detail.timestamp)} · {detail&&paymentLabel(detail)}</DialogDescription>{detail&&<><div className="detail-customer"><div className="avatar">{detail.customer?.[0]?.toUpperCase()||<CupSoda size={20}/>}</div><div><b>{detail.customer||'Walk-in customer'}</b><p className="muted">{detail.session_voided?'Selling session voided · excluded from hourly stats':detail.session_id?'Logged during open hours':'Logged outside tracked hours'}</p></div></div>{detail.items.map((i,n)=><div className="detail-line" key={n}><span>{i.quantity} × {i.name}<small>{money(i.price)} each{i.product_id===null?' · Custom item':''}</small></span><strong>{money(i.quantity*i.price)}</strong></div>)}{detail.total!==detail.items.reduce((a,i)=>a+i.quantity*i.price,0)&&<div className="detail-line"><span>Adjustment from item subtotal</span><strong>{detail.total-detail.items.reduce((a,i)=>a+i.quantity*i.price,0)>0?'+':''}{money(detail.total-detail.items.reduce((a,i)=>a+i.quantity*i.price,0))}</strong></div>}<div className="detail-total"><b>Amount paid</b><strong>{money(detail.total)}</strong></div>{!!detail.did_upsell&&<div className="note upsell-summary"><span className="pill upsell-badge">Upsold sale</span>{detail.upsell_pitch&&<div><b>What you said</b><p>{detail.upsell_pitch}</p></div>}{detail.upsell_items&&<div><b>What you upsold</b><p>{detail.upsell_items}</p></div>}</div>}{detail.notes&&<div className="note"><b>Something special</b><p>{detail.notes}</p></div>}{detail.photo&&<img className="customer-photo" src={'/api/photos/'+detail.id} alt={`Photo attached to ${detail.customer||'customer'} sale`}/>}<button className="quiet danger" onClick={()=>setVoidOpen(true)}>Void this sale</button></>}</DialogContent></Dialog>
 <AlertDialog open={!!deleteProduct} onOpenChange={v=>{if(!v&&!busy)setDeleteProduct(null)}}><AlertDialogContent><AlertDialogTitle>Delete {deleteProduct?.name}?</AlertDialogTitle><AlertDialogDescription>This removes the product from your menu and sale form. Past sales and statistics stay saved. You can restore it from Deleted items.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep product</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();if(deleteProduct)void removeProduct(deleteProduct)}}>{busy?'Deleting…':'Delete product'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={voidOpen} onOpenChange={setVoidOpen}><AlertDialogContent><AlertDialogTitle>Void this sale?</AlertDialogTitle><AlertDialogDescription>This removes it from your sales log and statistics. Use this to correct an accidental or duplicate entry.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep sale</AlertDialogCancel><AlertDialogAction onClick={async()=>{if(!detail)return;try{await action({action:'void',id:detail.id});setDetail(null);reload();toast.success('Sale voided.')}catch(e){toast.error((e as Error).message)}}}>Void sale</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
function Metric({title,value,sub,featured,icon}:{title:string;value:string;sub:string;featured?:boolean;icon?:React.ReactNode}){return <article className={'metric '+(featured?'featured':'')}><span>{title}{icon}</span><strong>{value}</strong><small>{sub}</small></article>}
function SalesTable({sales,onOpen}:{sales:Sale[];onOpen:(s:Sale)=>void}){if(!sales.length)return <Blank title="No sales here yet." text="Your saved sales, customer details, and notes will appear here."/>;return <><div className="mobile-sales">{sales.map(s=><button type="button" className="sale-card" key={s.id} onClick={()=>onOpen(s)}><span className="sale-card-top"><b>{s.customer||'Walk-in customer'}</b><strong>{money(s.total)}</strong></span><span className="sale-card-items">{s.items.map(i=>`${i.quantity} × ${i.name}`).join(', ')}</span><span className="sale-card-bottom"><span>{when(s.timestamp)}</span><span>{paymentLabel(s)}{s.did_upsell?' · Upsold':''}</span></span></button>)}</div><div className="desktop-sales"><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>What they loved</TableHead><TableHead>Date & time</TableHead><TableHead>Payment</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{sales.map(s=><TableRow key={s.id}><TableCell><button className="customer-button" onClick={()=>onOpen(s)}><span className="avatar">{s.photo?<ImageIcon size={17}/>:s.customer?.[0]?.toUpperCase()||<CupSoda size={17}/>}</span><span><b>{s.customer||'Walk-in customer'}</b><small>{s.did_upsell?'Upsold sale':s.notes?'Has a special note':'View sale'}</small></span></button></TableCell><TableCell>{s.items.map(i=>`${i.quantity} × ${i.name}`).join(', ')}</TableCell><TableCell className="nowrap">{when(s.timestamp)}</TableCell><TableCell><span className="payment-pill">{paymentLabel(s)}</span></TableCell><TableCell className="text-right"><b>{money(s.total)}</b></TableCell></TableRow>)}</TableBody></Table></div></>}
function HourlyChart({rows}:{rows:{hour:number;revenue:number;sales:number}[]}){const max=Math.max(100,...rows.map(r=>r.revenue));return <div className="hourly-chart" role="img" aria-label={rows.length?'Hourly revenue. '+rows.map(r=>`${hourLabel(r.hour)}: ${money(r.revenue)}`).join('; '):'No hourly revenue yet'}><div className="bar-grid">{Array.from({length:24},(_,h)=>{const row=rows.find(r=>r.hour===h),v=row?.revenue||0;return <div className="hour-column" key={h}><div className={'hour-bar '+(v===max?'best':'')} style={{height:`${v?Math.max(2,v/max*100):2}%`}} title={`${hourLabel(h)}: ${money(v)} · ${row?.sales||0} sales`}/></div>})}</div><div className="chart-axis">{[0,4,8,12,16,20,23].map(h=><span key={h}>{hourLabel(h)}</span>)}</div></div>}
function RevenueChart({rows}:{rows:{day:string;revenue:number;sales:number}[]}){const byDay=new Map(rows.map(r=>[r.day,r]));const filled:typeof rows=[];for(let d=rows[0].day;d<=rows[rows.length-1].day;d=addDays(d,1)){filled.push(byDay.get(d)||{day:d,revenue:0,sales:0});}rows=filled;const max=Math.max(100,...rows.map(r=>r.revenue)),min=Date.parse(rows[0].day),span=Math.max(86400000,Date.parse(rows[rows.length-1].day)-min);const points=rows.map(r=>({x:44+(Date.parse(r.day)-min)/span*650,y:192-r.revenue/max*150,...r}));const path=points.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ');return <div className="revenue-chart"><svg viewBox="0 0 720 240" role="img" aria-label={'Revenue by date: '+rows.map(r=>`${r.day} ${money(r.revenue)}`).join('; ')}><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#b5cd72" stopOpacity=".35"/><stop offset="1" stopColor="#b5cd72" stopOpacity="0"/></linearGradient></defs>{[0,.5,1].map(v=><g key={v}><line x1="44" x2="696" y1={192-v*150} y2={192-v*150} stroke="#e9ede6" strokeDasharray="4 5"/><text x="0" y={197-v*150} fill="#788371" fontSize="12">${Math.round(max*v/100)}</text></g>)}<path d={`${path} L${points[points.length-1].x},192 L44,192 Z`} fill="url(#chart-fill)"/><path d={path} fill="none" stroke="#486d37" strokeWidth="3" strokeLinejoin="round"/>{points.filter((_,i)=>rows.length<32||i===rows.length-1).map(p=><circle key={p.day} cx={p.x} cy={p.y} r="4" fill="#486d37" stroke="white" strokeWidth="2"><title>{p.day}: {money(p.revenue)} · {p.sales} sales</title></circle>)}<text x="44" y="227" fill="#788371" fontSize="13">{rows[0].day}</text><text x="694" y="227" textAnchor="end" fill="#788371" fontSize="13">{rows[rows.length-1].day}</text></svg></div>}
