"use client";
import {useEffect,useState} from 'react';
import {Clock3} from 'lucide-react';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
import {money,TIMEZONE} from '@/lib/stand';

type SellingSession={id:string;started:number;ended:number|null;active:number|null;voided:number|null;sales:number;revenue:number};
const timestamp=(t:number)=>new Intl.DateTimeFormat('en-US',{timeZone:TIMEZONE,year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'}).format(t);
const date=(t:number)=>new Intl.DateTimeFormat('en-US',{timeZone:TIMEZONE,year:'numeric',month:'short',day:'numeric'}).format(t);
function duration(ms:number){const seconds=Math.max(0,Math.floor(ms/1000));return `${Math.floor(seconds/3600)}h ${Math.floor(seconds/60)%60}m ${seconds%60}s`;}
export function SellingTimes({refresh,clock,onChange}:{refresh:number;clock:number;onChange:()=>void}){
 const [status,setStatus]=useState('all'),[page,setPage]=useState(0),[data,setData]=useState<{count:number;sessions:SellingSession[]}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[target,setTarget]=useState<SellingSession|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');fetch('/api/stand?'+new URLSearchParams({action:'sessions',status,page:String(page)}),{signal:abort.signal}).then(async res=>{const d=await res.json() as {count:number;sessions:SellingSession[];error?:string};if(!res.ok)throw new Error(d.error||'Could not load selling times.');return d}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[status,page,refresh,retry]);
 async function voidSession(){if(!target)return;setBusy(true);try{const res=await fetch('/api/stand',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'void-session',id:target.id})});const d=await res.json() as {error?:string};if(!res.ok)throw new Error(d.error||'Could not void this selling session.');setTarget(null);toast.success('Selling session voided. Your sales are still saved.');onChange()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel selling-times"><div className="panel-heading"><div><h2>Selling times</h2><p className="muted">Every time you opened and closed the stand. Times in {TIMEZONE}.</p></div><span className="pill">{data?.count??0} sessions</span></div>
 <div className="choice-buttons session-filters" role="group" aria-label="Filter selling times">{[{value:'all',label:'All sessions'},{value:'active',label:'Open now'},{value:'closed',label:'Closed'},{value:'voided',label:'Voided'}].map(s=><button key={s.value} type="button" aria-pressed={status===s.value} onClick={()=>{setStatus(s.value);setPage(0)}}>{s.label}</button>)}</div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setRetry(v=>v+1)}>Try again</button></div>}
 {loading?<p className="loading-line muted" role="status">Loading selling times…</p>:!error&&!data?.sessions.length?<div className="blank"><Clock3 size={30}/><h3>No selling sessions here yet.</h3><p>Use Open stand when you begin selling and Close stand when you finish.</p>{page>0&&<button className="secondary" onClick={()=>setPage(0)}>Go to first page</button>}</div>:!error&&<div className="session-grid">{data?.sessions.map(s=><article className={'session-card '+(s.voided?'is-voided':'')} key={s.id}><div className="session-card-heading"><h3>{date(s.started)}</h3><span className="pill">{s.voided?'Voided':s.active?'Open now':'Closed'}</span></div><dl className="session-timestamps"><div><dt>Opened</dt><dd><time dateTime={new Date(s.started).toISOString()}>{timestamp(s.started)}</time></dd></div><div><dt>Closed</dt><dd>{s.ended!==null?<time dateTime={new Date(s.ended).toISOString()}>{timestamp(s.ended)}</time>:'Still open'}</dd></div>{s.voided!==null&&<div><dt>Voided</dt><dd><time dateTime={new Date(s.voided).toISOString()}>{timestamp(s.voided)}</time></dd></div>}</dl><div className="session-card-footer"><div><span>Duration{s.active?' · running':''}</span><strong>{duration((s.ended??clock)-s.started)}</strong><small>{s.sales} sales · {money(s.revenue)}</small></div>{!s.voided&&<button className="secondary session-void" disabled={busy} onClick={()=>setTarget(s)}>Void session</button>}</div>{!!s.voided&&<p className="session-void-note">Excluded from hourly statistics. Sales remain saved.</p>}</article>)}</div>}
 <div className="pagination"><span>{data?.count?`Showing ${page*25+1}–${Math.min((page+1)*25,data.count)} of ${data.count}`:'No sessions'}</span><div><button className="secondary" disabled={!page||loading} onClick={()=>setPage(v=>v-1)}>Previous</button><button className="secondary" disabled={loading||(page+1)*25>=(data?.count||0)} onClick={()=>setPage(v=>v+1)}>Next</button></div></div>
 <AlertDialog open={!!target} onOpenChange={v=>{if(!v&&!busy)setTarget(null)}}><AlertDialogContent><AlertDialogTitle>Void this selling session?</AlertDialogTitle><AlertDialogDescription>Opened {target&&timestamp(target.started)}. This excludes the session’s selling time and its revenue from the hourly average. Its sales and total revenue stay saved.{target?.active?' Your stand will also be closed.':''}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep session</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void voidSession()}}>{busy?'Voiding…':'Void session'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>
}
